feat: set ruby version from .ruby-version

diff --git a/ws/cnb/bin/build b/ws/cnb/bin/build
--- a/ws/cnb/bin/build
+++ b/ws/cnb/bin/build
@@ -1,18 +1,24 @@
 #!/usr/bin/env bash
 set -eo pipefail
 
+wget -qO /tmp/jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 && chmod +x /tmp/jq
+wget -qO /tmp/yj https://github.com/sclevine/yj/releases/download/v2.0/yj-linux && chmod +x /tmp/yj
 echo "---> Ruby buildpack"
 
 layersdir=$1
+plan=$3
 
 echo "---> Downloading and extracting Ruby"
 rubylayer="$layersdir"/ruby
 mkdir -p "$rubylayer"
-ruby_url=https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-2.5.1.tgz
+ruby_version=$(cat "$plan" | /tmp/yj -t | /tmp/jq -r '.entries[] | select(.name == "ruby") | .version')
+echo "---> Downloading and extracting Ruby $ruby_version"
+ruby_url=https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-18/ruby-$ruby_version.tgz
 wget -q -O - "$ruby_url" | tar -xzf - -C "$rubylayer"
 
 
 echo -e 'launch = true' > "$rubylayer.toml"
+echo -e "launch = true\nmetadata = \"$ruby_version\"" > "$rubylayer.toml"
 
 export PATH="$rubylayer"/bin:$PATH
 export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}"$rubylayer/lib"
@@ -21,7 +27,23 @@ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}"$rubylayer/lib"
 echo "---> Installing bundler"
 gem install bundler --no-ri --no-rdoc
 
+# bundle layer for cache
 echo "---> Installing gems"
-bundle install
+bundlerlayer="$layersdir/bundler"
+local_bundler_checksum=$(sha256sum Gemfile.lock | cut -d ' ' -f 1) 
+remote_bundler_checksum=$(cat "$bundlerlayer.toml" | /tmp/yj -t | /tmp/jq -r .metadata 2>/dev/null || echo 'not found')
+
+if [[ -f Gemfile.lock && $local_bundler_checksum == $remote_bundler_checksum ]] ; then
+    # Determine if no gem dependencies have changed, so it can reuse existing gems without running bundle install
+    echo "---> Reusing gems"
+    bundle config --local path "$bundlerlayer" >/dev/null
+    bundle config --local bin "$bundlerlayer/bin" >/dev/null
+else
+    # Determine if there has been a gem dependency change and install new gems to the bundler layer; re-using existing and un-changed gems
+    echo "---> Installing gems"
+    mkdir -p "$bundlerlayer"
+    echo -e "cache = true\nlaunch = true\nmetadata = \"$local_bundler_checksum\"" > "$bundlerlayer.toml"
+    bundle install --path "$bundlerlayer" --binstubs "$bundlerlayer/bin"
+fi
 
 echo 'processes = [{ type = "web", command = "bundle exec ruby app.rb"}]' > "$layersdir/launch.toml"
